2025-03-18 13:48:47.675 [info] Started local extension host with pid 25425.
2025-03-18 13:48:48.407 [error] Extension 'ms-python.debugpy CANNOT USE these API proposals 'portsAttributes, debugVisualization, contribViewsWelcome'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2025-03-18 13:48:48.407 [error] Extension 'ms-python.python CANNOT USE these API proposals 'contribEditorContentMenu, quickPickSortByLabel, testObserver, quickPickItemTooltip, terminalDataWriteEvent, terminalExecuteCommandEvent, codeActionAI, notebookReplDocument, notebookVariableProvider'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2025-03-18 13:48:48.408 [error] Extension 'ms-toolsai.jupyter-renderers CANNOT USE these API proposals 'contribNotebookStaticPreloads'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2025-03-18 13:48:48.452 [error] [ms-python.python]: editor/content is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["contribEditorContentMenu"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
2025-03-18 13:48:50.099 [error] Error while getting the latest version for the extension ms-python.debugpy. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.099 [error] Error while getting the latest version for the extension ms-python.python. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.099 [error] Error while getting the latest version for the extension ms-toolsai.jupyter. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.099 [error] Error while getting the latest version for the extension ms-toolsai.jupyter-keymap. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.100 [error] Error while getting the latest version for the extension ms-toolsai.jupyter-renderers. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.100 [error] Error while getting the latest version for the extension ms-toolsai.vscode-jupyter-cell-tags. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.100 [error] Error while getting the latest version for the extension ms-toolsai.vscode-jupyter-slideshow. Cannot read properties of undefined (reading 'replace')
2025-03-18 13:48:50.549 [error] An unknown error occurred. Please consult the log for more details.
2025-03-18 13:48:50.759 [info] [perf] Render performance baseline is 27ms
2025-03-18 14:38:58.039 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at Cf.getLineMaxColumn (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:253:112)
    at vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2001:13251
    at HI._computeFn (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:24260)
    at HI.q (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:25793)
    at HI.get (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:25545)
    at HI.reportChanges (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:15998)
    at rse.endUpdate (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:22892)
    at HI.endUpdate (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:26591)
    at _5.finish (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:17858)
    at Hi (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:17251)
2025-03-18 14:39:36.913 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at Cf.getLineMaxColumn (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:253:112)
    at vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2001:13251
    at HI._computeFn (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:24260)
    at HI.q (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:25793)
    at HI.get (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:25545)
    at HI.reportChanges (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:15998)
    at rse.endUpdate (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:22892)
    at HI.endUpdate (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:26591)
    at _5.finish (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:17858)
    at Hi (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:31:17251)
2025-03-18 14:48:18.390 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:30:02.198 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:32:45.109 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:34:54.099 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:34:59.967 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:38:34.827 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:33.020 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:34.934 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:52.662 [error] UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:55.148 [error] UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value: Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
