2025-03-18 13:48:48.461 [info] Extension host with pid 25425 started
2025-03-18 13:48:48.461 [info] Skipping acquiring lock for /home/bartosh/.config/Code - OSS/User/workspaceStorage/3c356c74365a5d6292f2b69356900c36.
2025-03-18 13:48:48.649 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-03-18 13:48:48.671 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.debugpy
2025-03-18 13:48:48.943 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
2025-03-18 13:48:49.367 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-03-18 13:48:49.374 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-03-18 13:48:49.454 [error] Activating extension ms-python.debugpy failed due to an error:
2025-03-18 13:48:49.454 [error] Error: Extension 'ms-python.debugpy' CANNOT use API proposal: portsAttributes.
Its package.json#enabledApiProposals-property declares:  but NOT portsAttributes.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.debugpy
	at N (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:106:19035)
	at Object.registerPortAttributesProvider (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:172:55709)
	at t.registerDebugger (/home/bartosh/.vscode-oss/extensions/ms-python.debugpy-2025.4.1-linux-x64/dist/extension.js:2:846581)
	at e.activate (/home/bartosh/.vscode-oss/extensions/ms-python.debugpy-2025.4.1-linux-x64/dist/extension.js:2:1098040)
	at Ww.kb (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:15216)
	at Ww.jb (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:14923)
	at file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:13081
	at async pw.n (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:13415)
	at async pw.m (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:13378)
	at async pw.l (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:12834)
2025-03-18 13:48:49.528 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-03-18 13:48:49.571 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-03-18 13:48:49.654 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-03-18 13:48:49.727 [info] Eager extensions activated
2025-03-18 13:48:49.746 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-03-18 13:48:49.748 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-03-18 13:48:50.548 [error] Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at N (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:106:19035)
	at get testResults (file:///usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:172:39547)
	at C.activate (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:908493)
	at /home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:2457
	at Array.map (<anonymous>)
	at v.activateWorkspace (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:2447)
2025-03-18 13:48:52.841 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebookSerializer:jupyter-notebook'
2025-03-18 13:48:52.962 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-cell-tags, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-03-18 13:48:52.966 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-slideshow, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-03-18 14:36:27.314 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2025-03-18 14:36:27.331 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2025-03-18 14:36:27.842 [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
2025-03-18 14:48:18.388 [error] [ms-python.python] provider FAILED
2025-03-18 14:48:18.389 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 14:48:19.011 [error] [ms-python.python] provider FAILED
2025-03-18 14:48:19.011 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:27:57.483 [error] [ms-python.python] provider FAILED
2025-03-18 15:27:57.483 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:30:02.195 [error] [ms-python.python] provider FAILED
2025-03-18 15:30:02.195 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:30:02.955 [error] [ms-python.python] provider FAILED
2025-03-18 15:30:02.955 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:32:45.095 [error] [ms-python.python] provider FAILED
2025-03-18 15:32:45.095 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:32:45.107 [error] [ms-python.python] provider FAILED
2025-03-18 15:32:45.107 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:34:54.095 [error] [ms-python.python] provider FAILED
2025-03-18 15:34:54.096 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:34:59.965 [error] [ms-python.python] provider FAILED
2025-03-18 15:34:59.965 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:35:00.963 [error] [ms-python.python] provider FAILED
2025-03-18 15:35:00.964 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:35:51.874 [error] [ms-python.python] provider FAILED
2025-03-18 15:35:51.874 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:38:34.824 [error] [ms-python.python] provider FAILED
2025-03-18 15:38:34.824 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:39:01.692 [error] [ms-python.python] provider FAILED
2025-03-18 15:39:01.693 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:41:30.542 [error] [ms-python.python] provider FAILED
2025-03-18 15:41:30.542 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:49:49.967 [error] [ms-python.python] provider FAILED
2025-03-18 15:49:49.967 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:33.016 [error] [ms-python.python] provider FAILED
2025-03-18 15:52:33.016 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:33.542 [error] [ms-python.python] provider FAILED
2025-03-18 15:52:33.542 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:33.919 [error] [ms-python.python] provider FAILED
2025-03-18 15:52:33.920 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:52:34.930 [error] [ms-python.python] provider FAILED
2025-03-18 15:52:34.931 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:48.659 [error] [ms-python.python] provider FAILED
2025-03-18 15:55:48.659 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:48.664 [error] [ms-python.python] provider FAILED
2025-03-18 15:55:48.664 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:52.661 [error] [ms-python.python] provider FAILED
2025-03-18 15:55:52.661 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-18 15:55:55.131 [error] [ms-python.python] provider FAILED
2025-03-18 15:55:55.131 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/bartosh/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
